version: '3'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '9000:9000'
    depends_on:
      - mongodb
    environment:
      DB_URL: mongodb://mongodb:27017/namedb
  mongodb:
    container_name: mongodb
    image: mongo:4.4.18
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: