version: '3'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '9000:9000'
    links:
      - mongodb
  mongo:
    container_name: mongodb
    image: mongo:4.4.18
    ports:
      - '27017:27017'