version: '3'
services:
  mongodb_container:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: TestAuth
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container_testauth:/data/db
    restart: always

volumes:
  mongodb_data_container_testauth: